### ISSUE TITLE
Add variable for git host line specifier

### ISSUE THREAD

**Issue by sidewinder12s** [alexander-yu/vscode-open#4]
Is there a way to configure open with the old behavior of not using a `#` to indicate line number? Or add a configurable variable for the line specifier that defaults to `#`

I use a not GitHub code repository and it doesn't use a `#` in how it specifies the line number.

**Comment by alexander-yu** [comment]
Yeah, can do!

For simplicity, I'll probably just revert that change, meaning that `${editor:lines}` will just output `1-4` instead of `#1-4` — similarly, for consistency I'll probably also change `${regex:lines}` also not include the `#` as part of the regex.

Out of curiosity, what does it use to specify line numbers?

**Comment by sidewinder12s** [comment]
`$` for some reason :)

**Comment by alexander-yu** [comment]
Ahh gotcha, I've seen that before. Just added the feature via the `lineSeparator` setting; it's treated as a regex so for dollar signs I'd recommend you do `lineSeparator: "\\$"` in order to escape.

**Comment by alexander-yu** [comment]
On second though, will push out a patch so that it's automatically escaped.
